package rules

import com.diabetes.facts.Patient;
import com.diabetes.facts.Conclusion;

/* Общие правила, которые связаны с осложнениями всех типов сахарного диабета */ 
rule "1. Hidden Hyperglycemia Pattern"
when
    $p : Patient(fatigue == true, blurredVision == true, slowHealing == true, thirst == false)
then
    insert(new Conclusion(
        "Вероятна хроническая скрытая гипергликемия без выраженной жажды."
    ));
    System.out.println("RULE FIRED: 1. Hidden Hyperglycemia Pattern");
end

rule "2. Vision Complications Risk"
when
    $p : Patient(blurredVision == true, highSugar == true)
then
    insert(new Conclusion("Возможны осложнения на сетчатке — направить к офтальмологу."));
    System.out.println("RULE FIRED: 2. Vision Complications Risk");
end

rule "3. Neuropathy Risk"
when
    $p : Patient(numbness == true, fatigue == true)
then
    insert(new Conclusion("Симптомы соответствуют нейропатии — требуется неврологическая оценка и скрининг невропатии."));
    System.out.println("RULE FIRED: 3. Neuropathy Risk");
end

rule "4. Dehydration Risk"
when
    $p : Patient(frequentUrination == true, thirst == true)
then
    insert(new Conclusion("Вероятна дегидратация — рекомендовано восполнение жидкости и мониторинг электролитов."));
    System.out.println("RULE FIRED: 4. Dehydration Risk");
end

rule "5. Cardiovascular Risk"
when
    $p : Patient(bmi > 28, fatigue == true)
then
    insert(new Conclusion("Рекомендуется оценка сердечно-сосудистой системы (ЭКГ, липиды)."));
    System.out.println("RULE FIRED: 5. Cardiovascular Risk");
end

rule "6. Combined Complications Risk"
when
    $p : Patient(blurredVision == true, numbness == true)
then
    insert(new Conclusion("Комбинация зрительных и нервных симптомов указывает на мультиорганные осложнения — комплексная диагностика необходима."));
    System.out.println("RULE FIRED: 6. Combined Complications Risk");
end

rule "7. Nocturnal Hypoglycemia Suspected"
when
    $p : Patient(nightSweats == true, fatigue == true, hunger == true, dizziness == false)
then
    insert(new Conclusion(
        "Возможна ночная гипогликемия с компенсаторным утренним истощением."));
    System.out.println("RULE FIRED: 7. Nocturnal Hypoglycemia Suspected");
end

rule "8. Unexpected Treatment Response"
when
    $p : Patient(fatigue == true, highSugar == true, bmi >= 18.5 && bmi <= 25)
then
    insert(new Conclusion("Высокий сахар при нормальном/низком BMI — проверить дозировки, соответствие терапии"));
    System.out.println("RULE FIRED: 8. Unexpected Treatment Response");
end

rule "9. Glycemic Variability Syndrome"
when
    Patient(fatigue == true, rapidHeartbeat == true, confusion == true, sweating == false)
then
    insert(new Conclusion(
        "Вероятны резкие колебания уровня глюкозы без типичных признаков гипо."
    ));
    System.out.println("RULE FIRED: 9. Glycemic Variability Syndrome");
end

rule "10. BMI Risk - Thirst"
when
    $p : Patient(bmi > 32, thirst == true)
then
    insert(new Conclusion("Высокий BMI и жажда — обращать внимание на метаболический контроль и объем жидкости."));
    System.out.println("RULE FIRED: 10. BMI Risk 1");
end

rule "11. BMI Risk - High Sugar"
when
    $p : Patient(bmi < 20, highSugar == true)
then
    insert(new Conclusion("Низкий BMI при высоком сахаре может указывать на худеющую форму диабета — рассмотреть аутоиммунный компонент."));
    System.out.println("RULE FIRED: 11. BMI Risk 2");
end

rule "12. BMI Risk - Fatique and Numbness"
when
    $p : Patient(bmi > 28, fatigue == true, numbness == true)
then
    insert(new Conclusion("Ожирение в сочетании с усталостью и онемением усиливает риск нейропатии и сердечно-сосудистых осложнений."));
    System.out.println("RULE FIRED: 12. BMI Risk 3");
end


rule "13. Hidden Pattern 1"
when
    $p : Patient(
        thirst == true,
        fatigue == true,
        frequentUrination == false
    )
then
    insert(new Conclusion("Жажда и усталость без полиурии — возможно нерегулярный прием пищи/колебания глюкозы, рекомендован дневник питания/глюкозы."));
    System.out.println("RULE FIRED: 13. Hidden Pattern 1");
end

rule "14. Hidden Pattern 2"
when
    $p : Patient(
        numbness == true,
        highSugar == false,
        lowSugar == false
    )
then
    insert(new Conclusion("Онемение при нормальном показателе сахара — искать другие причины нейропатии и скрытые периферические нарушения."));
    System.out.println("RULE FIRED: 14. Hidden Pattern 2");
end


/* 1 тип сахарного диабета */

rule "15. Basal Insulin Mismatch"
when
    $p : Patient(
        diabetesType == "Тип 1",
        nightSweats == true,
        hunger == true,
        fatigue == true,
        skippedMeals == false
    )
then
    insert(new Conclusion("Возможна несоответствующая базальная доза инсулина."));
    System.out.println("RULE FIRED: 15. Basal Insulin Mismatch");
end

rule "16. Bolus Timing Issue"
when
    $p : Patient(
        diabetesType == "Тип 1",
        lateEating == true,
        blurredVision == true,
        fatigue == true,
        thirst == false
    )
then
    insert(new Conclusion("Вероятна ошибка во времени введения болюсного инсулина."));
    System.out.println("RULE FIRED: 16. Bolus Timing Issue");
end

rule "17. Injection Absorption Problem"
when
    $p : Patient(
        diabetesType == "Тип 1",
        injectionSiteProblems == true,
        highSugar == false,
        fatigue == true,
        blurredVision == true
    )
then
    insert(new Conclusion("Нарушено всасывание инсулина из-за проблем с местом инъекции."));
    System.out.println("RULE FIRED: 17. Injection Absorption Problem");
end

/* Диабет 2 типа */

rule "18. Progressive Insulin Resistance"
when
    $p : Patient(
        diabetesType == "Тип 2",
        bmi > 30,
        fatigue == true,
        slowHealing == true,
        frequentUrination == false
    )
then
    insert(new Conclusion("Прогрессирующая инсулинорезистентность без классических симптомов."));
    System.out.println("RULE FIRED: 18. Progressive Insulin Resistance");
end

rule "19. Postprandial Hyperglycemia"
when
    $p : Patient(
        diabetesType == "Тип 2",
        lateEating == true,
        hunger == true,
        fatigue == true,
        thirst == false
    )
then
    insert(new Conclusion("Вероятна постпрандиальная гипергликемия."));
    System.out.println("RULE FIRED: 19. Postprandial Hyperglycemia");
end

rule "20. Diet-Induced Glycemic Instability"
when
    $p : Patient(
        diabetesType == "Тип 2",
        irregularEating == true,
        rapidHeartbeat == true,
        confusion == true
    )
then
    insert(new Conclusion("Колебания сахара вызваны нарушением режима питания."));
    System.out.println("RULE FIRED: 20. Diet-Induced Glycemic Instability");
end

rule "21. Early Neuropathy Without Pain"
when
    $p : Patient(
        numbness == true,
        neuropathyPain == false,
        fatigue == true,
        slowHealing == true
    )
then
    insert(new Conclusion("Ранняя стадия диабетической нейропатии без болевого синдрома."));
    System.out.println("RULE FIRED: 21. Early Neuropathy Without Pain");
end

rule "22. Autonomic Neuropathy Pattern"
when
    $p : Patient(
        rapidHeartbeat == true,
        dizziness == true,
        sweating == false,
        hunger == false
    )
then
    insert(new Conclusion("Вероятна автономная диабетическая нейропатия."));
    System.out.println("RULE FIRED: 22. Autonomic Neuropathy Pattern");
end

rule "23. Foot Ulcer Risk Without Ulcers"
when
    $p : Patient(
        numbness == true,
        slowHealing == true,
        infections == true,
        footUlcers == false
    )
then
    insert(new Conclusion("Высокий риск формирования диабетической стопы."));
    System.out.println("RULE FIRED: 23. Foot Ulcer Risk Without Ulcers");
end

rule "24. Early Diabetic Nephropathy"
when
    $p : Patient(
        kidneyIssues == false,
        highBloodPressure == true,
        nightSweats == true,
        fatigue == true
    )
then
    insert(new Conclusion("Вероятна ранняя стадия диабетической нефропатии."));
    System.out.println("RULE FIRED: 24. Early Diabetic Nephropathy");
end

rule "25. Compensatory Overeating Pattern"
when
    $p : Patient(
        skippedMeals == true,
        hunger == true,
        fatigue == true,
        poorDiet == false
    )
then
    insert(new Conclusion("Компенсаторное переедание как ответ на пропуски пищи."));
    System.out.println("RULE FIRED: 25. Compensatory Overeating Pattern");
end

rule "26. Reactive Hypoglycemia"
when
    $p : Patient(
        lateEating == true,
        rapidHeartbeat == true,
        sweating == true,
        confusion == true
    )
then
    insert(new Conclusion("Реактивная гипогликемия после позднего приема пищи."));
    System.out.println("RULE FIRED: 26. Reactive Hypoglycemia");
end

rule "27. Pseudo-Hypoglycemia"
when
    $p : Patient(
        dizziness == true,
        sweating == true,
        hunger == true,
        lowSugar == false
    )
then
    insert(new Conclusion("Псевдогипогликемия при резком снижении сахара."));
    System.out.println("RULE FIRED: 27. Pseudo-Hypoglycemia");
end


rule "28. Hypoglycemia Unawareness"
when
    $p : Patient(
        lowSugar == false,
        confusion == true,
        sweating == false,
        hunger == false
    )
then
    insert(new Conclusion("Потеря распознавания гипогликемии."));
    System.out.println("RULE FIRED: 28. Hypoglycemia Unawareness");
end

/* Системные правила */

rule "29. Long-Term Poor Control"
when
    $p : Patient(
        slowHealing == true,
        infections == true,
        blurredVision == true,
        fatigue == true
    )
then
    insert(new Conclusion("Длительно неудовлетворительный контроль диабета."));
    System.out.println("RULE FIRED: 29. Long-Term Poor Control");
end

rule "30. Therapy Ineffectiveness"
when
    $p : Patient(
        highSugar == false,
        lowSugar == false,
        fatigue == true,
        weightLoss == true
    )
then
    insert(new Conclusion("Возможная неэффективность текущей терапии."));
    System.out.println("RULE FIRED: 30. Therapy Ineffectiveness");
end

/* Гестационный диабет */

rule "31. Placental Insulin Resistance"
when
    $p : Patient(
        diabetesType == "Гестационный",
        pregnancyWeek > 24,
        fatigue == true,
        blurredVision == true,
        thirst == false
    )
then
    insert(new Conclusion("Вероятно усиление плацентарной инсулинорезистентности."));
    System.out.println("RULE FIRED: 31. Placental Insulin Resistance");
end

rule "32. Gestational - Insulin Resistance Warning"
when
    $p : Patient(
        diabetesType == "Гестационный",
        bmi > 28,
        highSugar == true
    )
then
    insert(new Conclusion("Гестационный диабет с ожирением и высоким сахаром — риск инсулинорезистентности, обсудить режим и наблюдение акушером."));
    System.out.println("RULE FIRED: 32. Gestational - Insulin Resistance Warning");
end

rule "33. Gestational - Fetal Risk Signal"
when
    $p : Patient(
        diabetesType == "Гестационный",
        highSugar == true
    )
then
    insert(new Conclusion("Высокий сахар при гестационном диабете повышает риск макросомии плода и осложнений при родах — координировать с акушерством."));
    System.out.println("RULE FIRED: 33. Gestational - Fetal Risk Signal");
end

rule "34. Gestational - Hydration Concern"
when
    $p : Patient(
        diabetesType == "Гестационный",
        frequentUrination == true,
        thirst == true
    )
then
    insert(new Conclusion("Беременная пациентка может быть дегидратирована — оценить статус жидкости и электролитов."));
    System.out.println("RULE FIRED: 34. Gestational - Hydration Concern");
end

rule "35. Gestational - Hypoglycemia Risk"
when
    $p : Patient(
        diabetesType == "Гестационный",
        fatigue == true,
        highSugar == false
    )
then
    insert(new Conclusion("У беременной возможна гипогликемия вследствие ограничений в питании или терапии — рекомендован мониторинг."));
    System.out.println("RULE FIRED: 35. Gestational - Hypoglycemia Risk");
end

rule "36. Hidden Infection Risk"
when
    $p : Patient(
        infections == true,
        fatigue == true,
        proteinInUrine == false,
        highSugar == false
    )
then
    insert(new Conclusion(
        "Наличие инфекций и усталость без повышенного сахара или протеинурии — возможная скрытая инфекция или иммунный дисбаланс. Рекомендовано обследование и контроль показателей крови."
    ));
    System.out.println("RULE FIRED: 36. Hidden Infection Risk in Gestational Diabetes");
end

rule "37. Autonomic Neuropathy Early Sign"
when
    $p : Patient(
        rapidHeartbeat == true,
        frequentUrination == false,
        highSugar == false
    )
then
    insert(new Conclusion("Учащённый пульс без гипергликемии и полиурии — возможные ранние признаки автономной нейропатии. Рекомендуется проверка вариабельности сердечного ритма."));
    System.out.println("RULE FIRED: 37. Autonomic Neuropathy Early Sign");
end

rule "38. Possible LADA Pattern"
when
    $p : Patient(
        diabetesType == "Тип 2",
        bmi < 25,
        weightLoss == true,
        fatigue == true,
        highSugar == true
    )
then
    insert(new Conclusion(
        "Низкий BMI, потеря веса и гипергликемия при формальном диагнозе диабета 2 типа могут указывать на LADA (латентный аутоиммунный диабет взрослых). Рекомендуется обследование на аутоантитела (GAD, IA-2) и пересмотр терапии."
    ));
    System.out.println("RULE FIRED: 38. Possible LADA Pattern");
end

rule "39. Preeclampsia Pattern"
when
    $p : Patient(
        diabetesType == "Гестационный",
        proteinInUrine == true,
        highBloodPressure == true,
        fetalGrowthIssues == true
    )
then
    insert(new Conclusion("Комбинация протеинурии, нарушений роста плода и гипертензии соответствует клинической картине преэклампсии на фоне гестационного диабета."));
    System.out.println("RULE FIRED: 39. Preeclampsia Pattern");
end

rule "40. Preterm Delivery Risk"
when
    $p : Patient(
        diabetesType == "Гестационный",
        pregnancyWeek < 37,
        fetalGrowthIssues == true,
        proteinInUrine == true
    )
then
    insert(new Conclusion("Сочетание осложнений повышает риск преждевременного родоразрешения. Требуется госпитализация и наблюдение."));
    System.out.println("RULE FIRED: 40. Preterm Delivery Risk");
end